### ISSUE TITLE
Add database information to `taxonomy` step

### ISSUE THREAD

**Issue by lmrodriguezr** [bio-miga/miga#152]
The `.intax` file should include (at least) the name and release tag (if any) of the reference database used

**Comment by gewenlong365** [comment]
How do I download the database file through the web page
Downloading in the software has been reporting errors
```
Exception: Net::ReadTimeout

DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/net-protocol-0.2.1/lib/net/protocol.rb:229:in `rbuf_fill'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/net-protocol-0.2.1/lib/net/protocol.rb:199:in `readuntil'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:1510:in `gets'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:1515:in `readline'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:462:in `getline'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:472:in `getmultiline'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:489:in `getresp'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:509:in `voidresp'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:674:in `block (2 levels) in retrbinary'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:335:in `with_binary'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:662:in `block in retrbinary'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/3.2.0/monitor.rb:202:in `synchronize'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/3.2.0/monitor.rb:202:in `mon_synchronize'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:661:in `retrbinary'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:799:in `getbinaryfile'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/common/net.rb:73:in `download_file_ftp'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli/action/db.rb:139:in `download_file'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli/action/db.rb:89:in `perform'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli/action.rb:32:in `launch'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli.rb:177:in `launch'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/bin/miga:12:in `<top (required)>'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/bin/miga:33:in `load'
DEBUG: /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/bin/miga:33:in `<main>'
/public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/net-protocol-0.2.1/lib/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<Socket:fd 5> (Net::ReadTimeout)
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/net-protocol-0.2.1/lib/net/protocol.rb:199:in `readuntil'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:1510:in `gets'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:1515:in `readline'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:462:in `getline'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:472:in `getmultiline'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:489:in `getresp'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:509:in `voidresp'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:674:in `block (2 levels) in retrbinary'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:335:in `with_binary'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:662:in `block in retrbinary'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/3.2.0/monitor.rb:202:in `synchronize'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/3.2.0/monitor.rb:202:in `mon_synchronize'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:661:in `retrbinary'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/lib/ruby/gems/3.2.0/gems/net-ftp-0.2.0/lib/net/ftp.rb:799:in `getbinaryfile'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/common/net.rb:73:in `download_file_ftp'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli/action/db.rb:139:in `download_file'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli/action/db.rb:89:in `perform'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli/action.rb:32:in `launch'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/lib/miga/cli.rb:177:in `launch'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/gems/miga-base-1.3.7.2/bin/miga:12:in `<top (required)>'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/bin/miga:33:in `load'
        from /public/Users/gewenlong/basic/conda_environment/environments/miga_test/share/rubygems/bin/miga:33:in `<main>'

# Host: gatech.microbial-genomes.org
# Manifest last update: 2023-05-01 13:20:42 -0400
# Database size: 30.1G (32.2G)
```
