### ISSUE TITLE
new miga version not working for conda env

### ISSUE THREAD

**Issue by jianshu93** [bio-miga/miga#170]
Hello Team,

I was using the conda version according to the tutorial to install miga in a conda environment. Since 1.3.1 or later, I always have this error when running whatever commands:

```
(miga) [jianshu@c391 Manganese_nature]$ time miga quality_wf --mytaxa-scan -c -t 12 -j 2 -o ./MAG_quality_miga ./MAG/*.fasta
[2023-08-27 09:09:26 -0500] Saving log to: /condo/ieg/jianshu/Manganese_nature/MAG_quality_miga/daemon/MiGA:MAG_quality_miga.output
Traceback (most recent call last):ts: 0.0% (0/2)     
	27: from /home/jianshu/data/miniconda3_new2/envs/miga/share/rubygems/bin/miga:23:in `<main>'
	26: from /home/jianshu/data/miniconda3_new2/envs/miga/share/rubygems/bin/miga:23:in `load'
	25: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/bin/miga:12:in `<top (required)>'
	24: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli.rb:177:in `launch'
	23: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli/action.rb:32:in `launch'
	22: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli/action/quality_wf.rb:33:in `perform'
	21: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli/action/wf.rb:250:in `run_daemon'
	20: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli/action/wf.rb:237:in `call_cli'
	19: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli.rb:177:in `launch'
	18: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli/action.rb:32:in `launch'
	17: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/cli/action/daemon.rb:91:in `perform'
	16: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/common/with_daemon.rb:139:in `daemon'
	15: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/common/with_daemon.rb:139:in `fork'
	14: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/common/with_daemon.rb:139:in `block in daemon'
	13: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/common/with_daemon.rb:170:in `launch_daemon_proc'
	12: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/daemons-1.4.0/lib/daemons.rb:198:in `run_proc'
	11: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/daemons-1.4.0/lib/daemons/cmdline.rb:124:in `catch_exceptions'
	10: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/daemons-1.4.0/lib/daemons.rb:199:in `block in run_proc'
	 9: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/daemons-1.4.0/lib/daemons/controller.rb:59:in `run'
	 8: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/daemons-1.4.0/lib/daemons/application.rb:307:in `start'
	 7: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/daemons-1.4.0/lib/daemons/application.rb:286:in `start_proc'
	 6: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/daemons-1.4.0/lib/daemons/application.rb:277:in `block in start_proc'
	 5: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/common/with_daemon.rb:170:in `block in launch_daemon_proc'
	 4: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/common/with_daemon.rb:194:in `in_loop'
	 3: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/daemon.rb:99:in `daemon_loop'
	 2: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/daemon.rb:314:in `flush!'
	 1: from /condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/daemon.rb:356:in `launch_job'
/condo/ieg/jianshu/miniconda3_new2/envs/miga/share/rubygems/gems/miga-base-1.3.8.2/lib/miga/daemon.rb:356:in `spawn': No such file or directory - cpus (Errno::ENOENT)
```

It seems there are some problems to find the daemon spawn module.

Thanks,

Best,

Jianshu

**Comment by jfq3** [comment]
I am not sure the conda version ever worked. There are a lot of conda recipes not built by the authors of the programs, and most of these do not work.
If you want to try miga, check out the Docker version. See instructions beginning with https://miga.gitbook.io/main-1/10WEtzu06EHwzW762VwX/miga-docker/installing-docker.
John Quensen

**Comment by lmrodriguezr** [comment]
Hello @jianshu93,

This doesn't look like an installation issue, but a configuration problem. Could you please share the file `~/.miga_daemon.json` either here or privately?

One simple solution might be to re-build the daemon definition file using `miga init`, but please let me check the existing one first so I can track the issue down.

Thanks!
Miguel.

**Comment by lmrodriguezr** [comment]
It appears this was not reproduced, but please let us know if it continues to be an issue
