### ISSUE TITLE
miga init error, Failed to install pyhmerr

### ISSUE THREAD

**Issue by tryfon** [bio-miga/miga#180]
Even though I have installed pyhmmer with the command `pip install --break-system-packages pyhmmer pyrodigal` as per instructions while running `miga init` I get the following 

> Testing sqlite3... yes
> Testing pyhmmer... no, installing
> Exception: Command failed with status 1:
> :
> OPT: {:stdout=>nil, :stderr=>nil, :dry=>false, :return=>:output, :raise=>true, :show_cmd=>false, :err2out=>true, :env=>{}, :source=>"/home/alexandra/.miga_modules"}
> CMD: . /home/alexandra/.miga_modules && /home/linuxbrew/.linuxbrew/bin/python3 -m pip install --user pyhmmer
> 
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/common/system_call.rb:40:in `run_cmd'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:94:in `run_cmd'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:257:in `install_library'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:215:in `check_and_install_library'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:203:in `block (2 levels) in check_libraries'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:202:in `each'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:202:in `block in check_libraries'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:200:in `each'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:200:in `check_libraries'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:82:in `perform'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action.rb:32:in `launch'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli.rb:182:in `launch'
> DEBUG: /home/alexandra/.gem/gems/miga-base-1.3.15.6/bin/miga:12:in `<top (required)>'
> DEBUG: /home/alexandra/.gem/ruby/3.3.0/bin/miga:25:in `load'
> DEBUG: /home/alexandra/.gem/ruby/3.3.0/bin/miga:25:in `<main>'
> /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/common/system_call.rb:40:in `run_cmd': Command failed with status 1: (MiGA::SystemCallError)
> :
> OPT: {:stdout=>nil, :stderr=>nil, :dry=>false, :return=>:output, :raise=>true, :show_cmd=>false, :err2out=>true, :env=>{}, :source=>"/home/alexandra/.miga_modules"}
> CMD: . /home/alexandra/.miga_modules && /home/linuxbrew/.linuxbrew/bin/python3 -m pip install --user pyhmmer
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:94:in `run_cmd'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:257:in `install_library'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:215:in `check_and_install_library'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:203:in `block (2 levels) in check_libraries'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:202:in `each'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:202:in `block in check_libraries'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:200:in `each'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:200:in `check_libraries'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action/init.rb:82:in `perform'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli/action.rb:32:in `launch'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/lib/miga/cli.rb:182:in `launch'
> from /home/alexandra/.gem/gems/miga-base-1.3.15.6/bin/miga:12:in `<top (required)>'
> from /home/alexandra/.gem/ruby/3.3.0/bin/miga:25:in `load'
> from /home/alexandra/.gem/ruby/3.3.0/bin/miga:25:in `<main>'

**Comment by tryfon** [comment]
Fixed it by running `/home/linuxbrew/.linuxbrew/bin/python3 -m pip install --user --break-system-packages pyhmerr`
