### ISSUE TITLE
Issue downloading draft Genomes

### ISSUE THREAD

**Issue by michoug** [bio-miga/miga#55]
Hi,
I tried to download draft genomes using this command 

miga get -P . --file test.tsv --universe web --db assembly_gz --ignore-dup --verbose -t genome

The content of test.tsv is

dataset comments        ids
Candidatus_Nitrosoarchaeum_koreensis_MY1_GCA_000220175  Assembly: GCA_000220175.2       ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/220/175/GCA_000220175.2_ASM22017v1/GCA_000220175.2_ASM22017v1_genomic.fna.gz
Thaumarchaeota_archaeon_SCGC_AAA007_O23_GCA_000402075   Assembly: GCA_000402075.1       ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/402/075/GCA_000402075.1_ASM40207v1/GCA_000402075.1_ASM40207v1_genomic.fna.gz

Here is the error I got 

```
Dataset: Candidatus_Nitrosoarchaeum_koreensis_MY1_GCA_000220175
Loading project.
Locating remote dataset.
Creating dataset.
Exception: undefined local variable or method 'map_to' for MiGA::RemoteDataset:Class

/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/lib/miga/remote_dataset.rb:91:in 'download_net'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/lib/miga/remote_dataset.rb:63:in 'download'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/lib/miga/remote_dataset.rb:188:in 'download'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/lib/miga/remote_dataset.rb:153:in 'save_to'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/actions/get.rb:80:in 'block in <top (required)>'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/actions/get.rb:62:in 'each'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/actions/get.rb:62:in '<top (required)>'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/bin/miga:205:in 'load'
/var/lib/gems/2.3.0/gems/miga-base-0.3.1.2/bin/miga:205:in '<top (required)>'
/usr/local/bin/miga:23:in 'load'
/usr/local/bin/miga:23:in '<main>
```

**Comment by michoug** [comment]
Thanks a lot !
