### ISSUE TITLE
MIGA Installation error

### ISSUE THREAD

**Issue by Tato14** [bio-miga/miga#93]
Hi! I am trying to install MIGA using conda.
Everything goes nicely but when I do `miga init` i got an error:
```
Testing Ruby (Required version: 2.1+)... sh: 2: /home/jg/.miga_modules: source: not found
/usr/bin
Testing Python... sh: 2: /home/jg/.miga_modules: source: not found
/home/jg/anaconda3/bin
Testing R... sh: 2: /home/jg/.miga_modules: source: not found
/usr/bin
Testing SQLite3... sh: 2: /home/jg/.miga_modules: source: not found
/home/jg/anaconda3/bin
Testing NCBI BLAST+... sh: 2: /home/jg/.miga_modules: source: not found
Where can I find it? [.] > 
I cannot find blastp sh: 2: /home/jg/.miga_modules: source: not found
Where can I find it? [.] > 
I cannot find blastp sh: 2: /home/jg/.miga_modules: source: not found
Where can I find it? [.] > /home/jg/ncbi-blast/
I cannot find blastp sh: 2: /home/jg/.miga_modules: source: not found
Where can I find it? [.] > /home/jg/ncbi-blast/bin
Exception: undefined local variable or method `rc_fh' for #<MiGA::Cli::Action::Init:0x000055c3bf721248>
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:191:in `block in find_software'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:181:in `loop'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:181:in `find_software'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:160:in `block (2 levels) in check_software_requirements'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:155:in `each_line'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:155:in `block in check_software_requirements'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:154:in `open'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:154:in `check_software_requirements'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action/init.rb:51:in `perform'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli/action.rb:33:in `launch'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/lib/miga/cli.rb:197:in `launch'
DEBUG: /var/lib/gems/2.5.0/gems/miga-base-0.6.0.0/bin/miga:10:in `<top (required)>'
DEBUG: /usr/local/bin/miga:23:in `load'
DEBUG: /usr/local/bin/miga:23:in `<main>'
```
Any ideas?

**Comment by lmrodriguezr** [comment]
Hello @Tato14 
Please edit the file `~/.miga_modules`, changing `source activate miga` -> `conda activate miga`

This is now updated [in the manual](https://manual.microbial-genomes.org/part2/requirements/conda).

I'll leave this issue open until we confirm the solution worked.

**Comment by Tato14** [comment]
Thanks! It worked nicely now.
